### ISSUE TITLE
Circle drawn on the hit marker does not disappear when cancelling

### ISSUE THREAD

**Issue by metametis** [stefanocudini/leaflet-search#293]
Hi,
I use the marker.circle option. When I click on the cancel icon in the search box, the circle stays on the map. 
However, when I make another research, the circle correctly disappears.
Is there a way to fix this ?
THank you,
Olivier

**Comment by hupe13** [comment]
Maybe is it to late: hideMarkerOnCollapse does the job.
But there is an other problem with it. If I zoom the map, the circle appears again. To prevent this change
https://github.com/stefanocudini/leaflet-search/blob/e5573af77780fbe5796f6ad5bf3175f6745b3ae4/src/leaflet-search.js#L903
to
```js
if(self._markerSearch && title != "") {
```

**Comment by metametis** [comment]
Thank you. I fixed the problem already but to tell the truth, I don't remember how...
Olivier

**Comment by hupe13** [comment]
I tested it again with my application, not that it is a special case. The first test is one geojson file with Points, the second is two geojson files with a MultiPolygon in each. Reliably the bug works only on the first search in the map with the geojson MultiPolygons. On the map with the Points it happens only once in a while, I haven't figured out yet under which condition. I will testing further.

**Comment by senavarreteh** [comment]
Hello. I have this same issue when i zoom, the circle just appears again. Couldn't fix the problem with what was suggested. 
Is there any other way to fix this?

Im currently using leaflet 1.9.3 and leaflet-search 3.0.9

Thanks for the help.
Sergio.

**Comment by hupe13** [comment]
I don't remember what I did specifically that the circle is now gone. Maybe this:

```js
          markerSearchControl.on("search:cancel", function(e) {
            if (e.target.options.hideMarkerOnCollapse) {
              //console.log(e.target._map);
              e.target._map.removeLayer(this._markerSearch);
            }
          });
```

**Comment by senavarreteh** [comment]
Hello, thanks for answering!

Unfortunately those lines of code did not solve my problem.

I think I have found the source.

https://github.com/stefanocudini/leaflet-search/blob/e5573af77780fbe5796f6ad5bf3175f6745b3ae4/src/leaflet-search.js#L901

The "once" listener has 2 types: moveend and zoomend. 

In previous versions of leaflet, if **one or the other is executed**, the listener is removed when the function finishes executing.

For the current version, **both events must be executed** to remove the listener. This causes the markers to be added again when zooming.

I don't know if this is intentional or a bug. For now I have solved the issue by removing the zoomend event from the listener (this does not affect my use cases).

You can try with this example and see two logs in your console (latest leaflet version).

`map.once('moveend zoomend', function (e) {
        console.log(e.type);
      });`

I hope this information is useful. And excuse my spelling mistakes.

Greetings.
